notifications:
  email: false

git:
  depth: 3
  
env: 
  global:
    - pyv=3.5
  
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      env: 
        - osv=MacOSX
      compiler: gcc
      before_install:
        - brew update && brew upgrade
        #https://github.com/Homebrew/homebrew-science/issues/1715
        - brew tap --repair && brew tap homebrew/science 
        - brew install octave
        
    - os: linux
      sudo: required
      dist: trusty
      env: 
        - osv=Linux
      before_install:
        - sudo add-apt-repository ppa:octave/stable -y
        - sudo apt-get update -qq
        - sudo apt-get install -qq octave octave-image


install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-$osv-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes --quiet conda
    - conda create --yes -n test python=$pyv
    - source activate test
    - pip -q install coveralls
    - python setup.py develop

script:
    - coverage run test/test.py

after_success:
    - coveralls
