notifications:
  email: false

git:
  depth: 3
  
env: 
  global:
    - pyv=3.5
  
matrix:
  include:
#    - os: osx
#      osx_image: xcode8.2
#      compiler: gcc
#      before_install:
#        - brew update && brew upgrade
#       #https://github.com/Homebrew/homebrew-science/issues/1715#
#        - brew tap --repair && brew tap homebrew/science 
#        - brew install octave
        
    - os: linux
      sudo: required
      dist: trusty
      before_install:
        - sudo add-apt-repository ppa:octave/stable -y
        - sudo apt update -qq
        - sudo apt install -qq octave octave-image


install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else 
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
      
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda create -n test python=$pyv
    - source activate test
    - pip -q install coveralls
    - python setup.py develop

script:
    - coverage run tests/test.py -v

after_success:
    - coveralls
